# Generated by Django 2.0.5 on 2018-08-06 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofileinfo',
            old_name='profilepic',
            new_name='profile_pic',
        ),
        migrations.RenameField(
            model_name='userprofileinfo',
            old_name='userinfo',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='bio',
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='portfolio_site',
            field=models.URLField(blank=True),
        ),
    ]
