# Generated by Django 2.0.5 on 2018-08-06 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0004_auto_20180806_1547'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofileinfo',
            old_name='user',
            new_name='user_info',
        ),
    ]
